# Do NOT update manually; changes here will be overwritten by Copier
_commit: 0f6de6d
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 8.0
rebel_module_groups: []
repo_description: CRM dan Project Integration
repo_name: CRM and Project Integration
repo_slug: opnsynid-crm-project
travis_apt_packages: []
travis_apt_sources: []
